# Generated by Django 4.2 on 2024-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='nota1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='nota2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
