# Generated by Django 4.2 on 2024-06-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0002_alter_detallenota_nota1_alter_detallenota_nota2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallenota',
            name='recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
