# Generated by Django 4.2 on 2024-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_alter_detallenota_nota1_alter_detallenota_nota2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='recuperacion'),
        ),
    ]
